### ISSUE TITLE
Alembic error: Can't locate revision identified by '34dd0bf00472'

### ISSUE THREAD

**Issue by rodrigoic23** [Nordeus/pushkin#50]
Hello, I'm trying to update the database to rise the server, but I'm receiving following error. I'd appreciate some help, I can't found what's the issue here.

> postgres@ar-sta023:/home/rodrigo/pushkin$ pushkin --configuration config.ini --upgrade-db
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Traceback (most recent call last):
  File "/usr/local/bin/pushkin", line 11, in <module>
    load_entry_point('pushkin==0.1.6.1', 'console_scripts', 'pushkin')()
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/pushkin/pushkin_cli.py", line 119, in main
    database.upgrade_database()
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/pushkin/database/database.py", line 55, in upgrade_database
    alembic_command.upgrade(alembic_cfg, "head")
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/util/compat.py", line 75, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/pushkin/database/migrations/env.py", line 76, in <module>
    run_migrations_online()
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/pushkin/database/migrations/env.py", line 71, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 321, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/command.py", line 243, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/script/base.py", line 338, in _upgrade_revs
    for script in reversed(list(revs))
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/script/base.py", line 174, in _catch_revision_errors
    compat.raise_from_cause(util.CommandError(resolution))
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/util/compat.py", line 128, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/script/base.py", line 143, in _catch_revision_errors
    yield
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/script/base.py", line 334, in _upgrade_revs
    revs = list(revs)
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/script/revision.py", line 642, in _iterate_revisions
    requested_lowers = self.get_revisions(lower)
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/script/revision.py", line 299, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/script/revision.py", line 304, in get_revisions
    for rev_id in resolved_id)
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/script/revision.py", line 304, in <genexpr>
    for rev_id in resolved_id)
  File "/var/lib/postgresql/.local/lib/python2.7/site-packages/alembic/script/revision.py", line 359, in _revision_for_ident
    resolved_id)
alembic.util.exc.CommandError: Can't locate revision identified by '34dd0bf00472'

**Comment by dprokic** [comment]
Hi! How did you install pushkin? I see you are executing upgrade as postgres user. Not sure which priviledges has that user. Can you install and upgrade pushkin as regular user?

**Comment by dprokic** [comment]
Also, which operating system do you have?

**Comment by rodrigoic23** [comment]
Hey, thanks for your answer. I've installed pushkin as my regular user following the quick start guide,  if i try to upgrade db as my regular user and as sudo, I get the same error. I have Ubuntu 17.04
For now, I've solved that by dropping db and create again.

Note: sorry if my english is not very well

**Comment by dprokic** [comment]
Hi Rodrigo,

Seems that you encountered a bug in alembic. I searched for your exception and people are usually suggesting solution that you did (drop db and upgrade from scratch). Thanks for using pushkin.

Regards,
Dejan
