### ISSUE TITLE
iOs issue, Connection to APN lost

### ISSUE THREAD

**Issue by rodrigoic23** [Nordeus/pushkin#51]
Hello everyone, the notifications for android are awesome, but I can't send it for iOs. 
/var/log/pushkin/pushkin.log says this: 

> 2017-10-25 17:02:17,902 ERROR Connection to APN lost, reconnecting and trying again
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pushkin-0.1.6.1-py2.7.egg/pushkin/sender/nordifier/pyapn2/client.py", line 48, in send_notification
    stream_id = self.__connection.request('POST', url, json_payload, headers)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 281, in request
    self.endheaders(message_body=body, final=True, stream_id=stream_id)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 546, in endheaders
    stream = self._get_stream(stream_id)
  File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 289, in _get_stream
    raise StreamResetError("Stream forcefully closed")
StreamResetError: Stream forcefully closed

Here is my config.ini:

> [ServerSpecific]
# Name of your application
game = PromoGo

# Id of pushkin instance
world_id = 1

# Default API port
port = 8887

[Messenger]
# if true, gcm clients will not receive notifications
dry_run = false

# max batch size for apn notifications
apns_batch_size = 500

apns_topic = PromoGo
apns_certificate_path = /home/promogo/pushkin/prod_push_nopass.pem
gcm_access_key = AAAAOfz579c:APA91bF8ekMFcL5P6AfzKYKk4nb_flPif1bLHgEc1zaxHxwK97T311Ln5Kk-orEs9JbOrayFpztI-CtOvBTiY9rde-KphsAA_yREX7MM2qIPISldJm$

# for future use
apns_sandbox = false
connection_error_retries = 3

# Baselink for your application sent with push notifications
base_deeplink_url = application_name.com

[RequestProcessor]
# queue limit for requests processor. See Monitoring API for reference
queue_limit = 50000
# Number of threads for request processor
request_processor_num_threads = 10

[Sender]
# queue limit for sender processor. See Monitoring API for reference
sender_queue_limit = 50000

enabled_senders =
  pushkin.sender.senders.ApnNotificationSender {"workers": 50}
  pushkin.sender.senders.GcmNotificationSender {"workers": 50}

[Log]
# log configuration
main_logger_name = pushkin
main_log_path = /var/log/pushkin/
notifications_logger_name = notifications
notification_log_path = /var/log/pushkin/notification/
notification_log_when_to_rotate = H
notification_log_rotate_suffix = %Y-%m-%d_%H
# notset, debug, info, warning, error, critical
main_log_level = DEBUG
keep_log_days = 7

[Database]
# database credentials
# to use unix socket set this to socket directory path
db_host = localhost
db_port = 5432
db_user = pushkin
db_name = pushkin
db_pass = pushkin
db_pool_size = 20
max_devices_per_user = 10
max_users_per_device = 1
[Event]
# event id of prebuilt login event
login_event_id = 4001
turn_off_notification_event_id = 4006

[RequestHandler]
# URLs for all request handlers
proto_event_handler_url = /post_events_proto
proto_notification_handler_url = /post_notification_proto
json_event_handler_url = /post_events_json
json_notification_handler_url = /post_notification_json
request_queue_handler_url = /get_request_queue
apn_sender_queue_handler_url = /get_apn_sender_queue
gcm_sender_queue_handler_url = /get_gcm_sender_queue
notification_post_processor_queue_handler_url = /get_notification_post_processor_queue

Could someone give me any clue? I'm not experienced with python, maybe it's a simple issue, but I can't figure it out.

Thank you.

**Comment by rodrigoic23** [comment]
SOLVED.
It was a wrong certificate type (dev / prod)
